### ISSUE TITLE
Suggestion #NewFeature - Persist sound volume configs locally 

### ISSUE THREAD

**Issue by wellington1993** [trungk18/angular-spotify#23]
I need to keep the same sound volume after close and reopen de site.

I'm stared recently with Angular, Maybe you(@trungk18) can help with a video tutorial about that.
I loved the project and I want to contribute with them in the future.

Thanks!

**Comment by trungk18** [comment]
@wellington1993 Thanks, that's a great suggestion. I'll add it in maybe tonight or tomorrow. I think it is already built in Spotify API, so what I need to do is to get the volume from Spotify API and set it along when initializing the Angular Spotify Web Player 😆

As I mentioned on the repo, there are some live stream sessions coming soon. And seems you have already waiting for the first one. Looking forward to seeing you there!

**Comment by wellington1993** [comment]
Thanks! @trungk18 I'm suggesting some thinks to learn Angular too! 

Nice work.

**Comment by trungk18** [comment]
@wellington1993 Sorry for not starting on that, I thought Spotify SDK will remember the volume when I connect to the player but turned out It didn't hehe. I'll need to store the volume inside localStorage then, but before getting into that. I need to finalize what I want to have in the storage too. Will get back into this issue in the next couple days.

**Comment by nikosanif** [comment]
Hi @trungk18! Is this considered as closed from #53 ?  If not, what else needs to be done to close it?

**Comment by trungk18** [comment]
@nikosanif Thanks for reminding me. I forgot to close it 🤣
